moving us to python 3 by default (console)

diff --git a/scripts/run_functional_tests b/scripts/run_functional_tests
--- a/scripts/run_functional_tests
+++ b/scripts/run_functional_tests
@@ -1,30 +1,27 @@
 #!/bin/bash
 
-source find_python.sh
+#source find_python.sh
 cd automation/regression
 
-if [ -z "$PYTHON" ]; then
-    echo "*** $PYTHON - python version is too old, 2.7 at least is required"
-else 
-    $PYTHON trex_unit_test.py --functional $@
-    if [ $? -eq 0 ]; then
-        printf "\n$PYTHON test succeeded\n\n"
-    else
-        printf "\n*** $PYTHON test failed\n\n"
-        exit -1
-    fi
-fi
+PYTHON=/usr/bin/python2
+PYTHON3=/auto/proj-pcube-b/apps/PL-b/tools/python3.4/bin/python3
 
-if [ -z "$PYTHON3" ]; then
-    echo "*** $PYTHON3 - python3 version required is 3.4 - skipping python3 test"
+# Python 2
+$PYTHON trex_unit_test.py --functional $@
+if [ $? -eq 0 ]; then
+    printf "\n$PYTHON test succeeded\n\n"
 else
-    $PYTHON3 trex_unit_test.py --functional $@
-    if [ $? -eq 0 ]; then
-        printf "\n$PYTHON3 test succeeded\n\n"
-    else
-        printf "\n*** $PYTHON3 test failed\n\n"
-        exit -1
-    fi
-
+    printf "\n*** $PYTHON test failed\n\n"
+    exit -1
 fi
+
+# Python 3
+$PYTHON3 trex_unit_test.py --functional $@
+if [ $? -eq 0 ]; then
+    printf "\n$PYTHON3 test succeeded\n\n"
+else
+    printf "\n*** $PYTHON3 test failed\n\n"
+    exit -1
+fi
+
 
