add to run_functional_tests --python2 and --python3 flags make stateful tree similar to stl : stf/trex_stf_lib and stf/examples change trex_client package: add profiles, use full stl dir. stl examples: now use stl_path.STL_PROFILES_PATH variable regression: add higher timeout to rsync.

diff --git a/scripts/run_functional_tests b/scripts/run_functional_tests
--- a/scripts/run_functional_tests
+++ b/scripts/run_functional_tests
@@ -1,30 +1,36 @@
 #!/bin/bash
 
-source find_python.sh --python2
-cd automation/regression
 
-# Python 2
-echo Python2 test
-$PYTHON trex_unit_test.py --functional $@
-if [ $? -eq 0 ]; then
-    printf "\n$PYTHON test succeeded\n\n"
-else
-    printf "\n*** $PYTHON test failed\n\n"
-    exit -1
+if [[ $@ =~ '--python2' || ! $@ =~ '--python3' ]]; then
+    source find_python.sh --python2
+    cd automation/regression
+
+    # Python 2
+    echo Python2 test
+    $PYTHON trex_unit_test.py --functional $@
+    if [ $? -eq 0 ]; then
+        printf "\n$PYTHON test succeeded\n\n"
+    else
+        printf "\n*** $PYTHON test failed\n\n"
+        exit -1
+    fi
+    cd -
 fi
 
-cd -
-source find_python.sh --python3
-cd -
+if [[ $@ =~ '--python3' || ! $@ =~ '--python2' ]]; then
+    source find_python.sh --python3
+    cd automation/regression
 
-# Python 3
-echo Python3 test
-$PYTHON trex_unit_test.py --functional $@
-if [ $? -eq 0 ]; then
-    printf "\n$PYTHON test succeeded\n\n"
-else
-    printf "\n*** $PYTHON test failed\n\n"
-    exit -1
+    # Python 3
+    echo Python3 test
+    $PYTHON trex_unit_test.py --functional $@
+    if [ $? -eq 0 ]; then
+        printf "\n$PYTHON test succeeded\n\n"
+    else
+        printf "\n*** $PYTHON test failed\n\n"
+        exit -1
+    fi
+    cd -
 fi
 
 
