t-rex-64: better check of return status of trex-cfg dpdk_setup_ports.py: fix incorrect behavior in several scenarios
Change-Id: I1582ab1840a940c2134e9d741e51bc405115dad0
Signed-off-by: Yaroslav Brustinov <ybrustin@cisco.com>

diff --git a/scripts/t-rex-64 b/scripts/t-rex-64
--- a/scripts/t-rex-64
+++ b/scripts/t-rex-64
@@ -9,23 +9,25 @@ EXTRA_INPUT_ARGS=""
 
 ./trex-cfg $INPUT_ARGS
 RESULT=$?
+
 if [ $RESULT -eq 255 ]; then
   echo "ERROR encountered while configuring trex system"
   exit $RESULT
-fi
 
-if [ $RESULT -eq 2 ]; then
+elif [ $RESULT -eq 2 ]; then
   echo "ERROR encountered while configuring trex system"
   exit $RESULT
-fi
 
-if [ $RESULT -eq 64 ]; then
+elif [ $RESULT -eq 64 ]; then
   EXTRA_INPUT_ARGS="--ntacc-so"
-fi
 
-
-if [ $RESULT -eq 32 ]; then
+elif [ $RESULT -eq 32 ]; then
   EXTRA_INPUT_ARGS="--mlx5-so"
+
+elif [ $RESULT -ne 0 ]; then
+   echo "Bad return status from trex-cfg ($RESULT)"
+   echo "Configuration failed"
+   exit $RESULT
 fi
 
 if [[ ! "$INPUT_ARGS" =~ "--help" ]]; then
