Update waf and remove python2 support. some of the old external lib were keept for the sake of our old regresion
Signed-off-by: Hanoh Haim <hhaim@cisco.com>

diff --git a/linux_dpdk/b b/linux_dpdk/b
--- a/linux_dpdk/b
+++ b/linux_dpdk/b
@@ -1,29 +1,52 @@
 #! /bin/bash
 
 export WAFLOCK=.lock-wafbuild_dpdk
-waf=waf-2.0.18
-p2=${PYTHON:-${PYTHON2:-python2.7}}
-p3=${PYTHON3:-python3}
+waf=waf-2.0.21
+
+PYTHONS3_LOCAL=( python3 /usr/bin/python3 )
+PYTHONS3=( ${PYTHONS3_LOCAL[*]} /auto/proj-pcube-b/apps/PL-b/tools/python3.4/bin/python3 )
+
+function find_python3 {
+
+    if [ -n "$PYTHON3" ]; then 
+        PYTHON=$PYTHON3
+        return;
+    fi
+    # try different Python3 paths
+    PYTHONS="$@"
+    for PYTHON in ${PYTHONS[*]}; do
+        $PYTHON -c "import sys; ver = sys.version_info[0] * 10 + sys.version_info[1];sys.exit(ver < 33)" &> /dev/null
+        if [ $? -eq 0 ]; then
+            p3=$PYTHON
+            return
+        fi
+    done;
+
+    echo "*** Python3 version is too old, 3.3 or later is required"
+    exit -1
+}
+
+find_python3 ${PYTHONS3[*]} 
+if [ $? -ne 0 ]; then
+  echo "Python versions 2.7 or 3.3 at least required"
+  exit -1
+fi
 
 
 # try Pythons which can load waf
 
-if $p2 $waf --help &> /dev/null; then
-    $p2 $waf $@
-elif $p3 $waf --help &> /dev/null; then
+if $p3 $waf --help &> /dev/null; then
     $p3 $waf $@
 
 # waf can't be loaded, print the error with available Python
 
-elif which $p2 &> /dev/null; then
-    $p2 $waf $@
 elif which $p3 &> /dev/null; then
     $p3 $waf $@
 
 # no Python available
 
 else
-    echo Required Python 2.7 or 3
+    echo Required 3
     exit 1
 fi
 
diff --git a/scripts/run_functional_tests b/scripts/run_functional_tests
--- a/scripts/run_functional_tests
+++ b/scripts/run_functional_tests
@@ -2,41 +2,23 @@
 
 INPUT_ARGS=${@//--python[23]/}
 
-if [[ $@ =~ '--python2' || ! $@ =~ '--python3' ]]; then
-    source find_python.sh --python2
-    cd automation/regression
+source find_python.sh 
+cd automation/regression
 
-    echo Python2 test
-    $PYTHON trex_unit_test.py --functional $INPUT_ARGS
-    if [ $? -eq 0 ]; then
-        printf "\n$PYTHON test succeeded\n\n"
-    else
-        printf "\n*** $PYTHON test failed\n\n"
-        exit -1
-    fi
-    cd -
-    SKIP_GTESTS="-e test_gtests_"
+# check for Python 3.4 and above (--wireless requirement)
+$PYTHON -c "from abc import ABC" &> /dev/null
+if [ $? -eq 0 ]; then
+    WIRELESS='--wireless'
 fi
 
-if [[ $@ =~ '--python3' || ! $@ =~ '--python2' ]]; then
-    source find_python.sh --python3
-    cd automation/regression
-
-    # check for Python 3.4 and above (--wireless requirement)
-    $PYTHON -c "from abc import ABC" &> /dev/null
-    if [ $? -eq 0 ]; then
-        WIRELESS='--wireless'
-    fi
-
-    echo Python3 test
-    $PYTHON trex_unit_test.py --functional $WIRELESS $INPUT_ARGS $SKIP_GTESTS
-    if [ $? -eq 0 ]; then
-        printf "\n$PYTHON test succeeded\n\n"
-    else
-        printf "\n*** $PYTHON test failed\n\n"
-        exit -1
-    fi
-    cd -
+echo Python3 test
+$PYTHON trex_unit_test.py --functional $WIRELESS $INPUT_ARGS $SKIP_GTESTS
+if [ $? -eq 0 ]; then
+    printf "\n$PYTHON test succeeded\n\n"
+else
+    printf "\n*** $PYTHON test failed\n\n"
+    exit -1
 fi
+cd -
 
 
